export const POSITION_LIST_REQUEST = "POSITION_LIST_REQUEST";
export const POSITION_LIST_SUCCESS = "POSITION_LIST_SUCCESS";
export const POSITION_LIST_FAIL = "POSITION_LIST_FAIL";
export const POSITION_LIST_RESET = "POSITION_LIST_RESET";

export const ADMIN_CREATE_POSITION_REQUEST = "ADMIN_POSITION_REGISTER_REQUEST";
export const ADMIN_CREATE_POSITION_SUCCESS = "ADMIN_CREATE_POSITION_SUCCESS";
export const ADMIN_CREATE_POSITION_FAIL = "ADMIN_CREATE_POSITION_FAIL";
export const POSITION_CREATE_RESET = "ADMIN_CREATE_RESET";

export const POSITION_EDIT_REQUEST = "POSITION_EDIT_REQUEST";
export const POSITION_EDIT_SUCCESS = "POSITION_EDIT_SUCCESS";
export const POSITION_EDIT_FAIL = "POSITION_EDIT_FAIL";

export const POSITION_UPDATE_REQUEST = "POSITION_UPDATE_REQUEST";
export const POSITION_UPDATE_SUCCESS = "POSITION_UPDATE_SUCCESS";
export const POSITION_UPDATE_FAIL = "POSITION_UPDATE_FAIL";
export const POSITION_UPDATE_RESET = "POSITION_UPDATE_RESET";

export const POSITION_DELETE_REQUEST = "POSITION_DELETE_REQUEST";
export const POSITION_DELETE_SUCCESS = "POSITION_DELETE_SUCCESS";
export const POSITION_DELETE_FAIL = "POSITION_DELETE_FAIL";