export const ROLE_LIST_REQUEST = "ROLE_LIST_REQUEST";
export const ROLE_LIST_SUCCESS = "ROLE_LIST_SUCCESS";
export const ROLE_LIST_FAIL = "ROLE_LIST_FAIL";
export const ROLE_LIST_RESET = "ROLE_LIST_RESET";

export const ADMIN_CREATE_ROLE_REQUEST = "ROLE_REGISTER_REQUEST";
export const ADMIN_CREATE_ROLE_SUCCESS = "ADMIN_CREATE_ROLE_SUCCESS";
export const ADMIN_CREATE_ROLE_FAIL = "ADMIN_CREATE_ROLE_FAIL";
export const ROLE_CREATE_RESET = "ADMIN_CREATE_RESET";